Leave:
  Item:
    ID: 347
    Name: '&bBack &aTo &bHub'
    Slot: 8
MySQL:
  enable: false
  host: localhost
  database: userdb
  username: user
  password: passhere
  port: 3306
coins-on-kill: 0
coins-on-win: 0
disable-fall-damage: true
bungee-mode: false
bungee-arena-name: none
Arenas:
  lab13:
    Lobby:
      Spawn:
        X: 580.5
        Y: 5.0
        Z: 140.5
        World: gameworld
        Pitch: 1.0500001
        Yaw: 179.84947
    Spawns:
      Counter: 16
      '1':
        X: 661.5
        Y: 4.0
        Z: 200.5
        World: gameworld
        Pitch: -0.7499996
        Yaw: -90.0
      '2':
        X: 679.2505792309744
        Y: 4.0
        Z: 189.74549142960242
        World: gameworld
        Pitch: 1.3500001
        Yaw: -178.49997
      '3':
        X: 660.141916251792
        Y: 4.0
        Z: 166.04885713421942
        World: gameworld
        Pitch: -1.0499997
        Yaw: -224.54996
      '4':
        X: 650.8270455372714
        Y: 4.0
        Z: 165.5645904440788
        World: gameworld
        Pitch: 3.0000014
        Yaw: -268.79987
      '5':
        X: 642.4085603942787
        Y: 4.0
        Z: 170.07502633456895
        World: gameworld
        Pitch: 1.0500009
        Yaw: -358.49994
      '6':
        X: 622.7750654387794
        Y: 4.0
        Z: 164.19126043539305
        World: gameworld
        Pitch: 1.5000076
        Yaw: -313.7999
      '7':
        X: 605.9484540071631
        Y: 4.0
        Z: 188.1773534619375
        World: gameworld
        Pitch: 0.600008
        Yaw: -359.84985
      '8':
        X: 595.5452841461884
        Y: 4.0
        Z: 209.0079950528333
        World: gameworld
        Pitch: -0.89999247
        Yaw: -179.99985
      '9':
        X: 609.4170713885392
        Y: 4.0
        Z: 219.5304726432608
        World: gameworld
        Pitch: 3.0000074
        Yaw: -45.449856
      '10':
        X: 630.0658989002479
        Y: 4.0
        Z: 244.65387558828849
        World: gameworld
        Pitch: 1.2000067
        Yaw: -89.39985
      '11':
        X: 646.9309608590073
        Y: 4.0
        Z: 230.90845529054093
        World: gameworld
        Pitch: 1.3500069
        Yaw: 45.150208
      '12':
        X: 638.7932875301668
        Y: 4.0
        Z: 217.2946603981696
        World: gameworld
        Pitch: 3.6000054
        Yaw: 178.95023
      '13':
        X: 624.7993687711444
        Y: 4.0
        Z: 214.22112048897714
        World: gameworld
        Pitch: 6.0000057
        Yaw: 225.15027
      '14':
        X: 625.3908766822868
        Y: 4.0
        Z: 187.7987252541409
        World: gameworld
        Pitch: 5.4000053
        Yaw: 180.30028
      '15':
        X: 640.5328424775179
        Y: 4.0
        Z: 191.58745657998065
        World: gameworld
        Pitch: 5.2500057
        Yaw: 2.2501526
arena-list:
- lab13
lab13:
  getKillsToWin: 25
  MinPlayers: 2
  Countdown: 25
  World: gameworld
  MaxPlayers: 20
  TimeLeft: 600
lobby:
  world: gameworld
  x: 117.5
  y: 7.0
  z: 418.5
Signs:
  lab13:
    X: 141.0
    Y: 5.0
    Z: 445.0
    World: gameworld
